/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './index.html',
        './src/**/*.{js,ts,jsx,tsx}',
    ],
    theme: {
        extend: {
            colors: {
                tertiary: '#904800',
                'surface-dim': '#d1dbec',
                'on-surface': '#121c28',
                'inverse-on-surface': '#eaf1ff',
                'surface-container': '#e5eeff',
                'on-tertiary-fixed-variant': '#713700',
                'tertiary-container': '#b55d00',
                'surface-bright': '#f8f9ff',
                'surface-container-lowest': '#ffffff',
                'tertiary-fixed': '#ffdcc5',
                'surface-tint': '#6d3bd7',
                'secondary-container': '#ffc329',
                'on-tertiary-fixed': '#301400',
                'on-tertiary-container': '#fffbff',
                background: '#f8f9ff',
                'primary-fixed-dim': '#d0bcff',
                primary: '#6b38d4',
                'error-container': '#ffdad6',
                'on-primary-container': '#fffbff',
                'secondary-fixed': '#ffdf9f',
                'on-secondary-container': '#6f5100',
                'primary-fixed': '#e9ddff',
                error: '#ba1a1a',
                'primary-container': '#8455ef',
                outline: '#7b7486',
                'tertiary-fixed-dim': '#ffb783',
                'surface-container-low': '#eef4ff',
                'on-surface-variant': '#494454',
                surface: '#f8f9ff',
                'on-background': '#121c28',
                'surface-container-high': '#dfe9fa',
                'surface-variant': '#d9e3f4',
                'inverse-primary': '#d0bcff',
                'on-primary': '#ffffff',
                secondary: '#795900',
                'surface-container-highest': '#d9e3f4',
                'on-error-container': '#93000a',
                'on-tertiary': '#ffffff',
                'secondary-fixed-dim': '#f9bd22',
                'inverse-surface': '#27313e',
                'on-primary-fixed-variant': '#5516be',
                'on-secondary': '#ffffff',
                'outline-variant': '#cbc3d7',
                'on-secondary-fixed': '#261a00',
                'on-error': '#ffffff',
                'on-primary-fixed': '#23005c',
                'on-secondary-fixed-variant': '#5c4300',
            },
            borderRadius: {
                DEFAULT: '1rem',
                lg: '2rem',
                xl: '3rem',
                full: '9999px',
            },
            spacing: {
                xs: '4px',
                sm: '12px',
                gutter: '24px',
                md: '24px',
                xl: '64px',
                'container-max': '1200px',
                base: '8px',
                lg: '40px',
            },
            fontFamily: {
                'headline-lg': ['Plus Jakarta Sans'],
                'label-lg': ['Plus Jakarta Sans'],
                'body-md': ['Plus Jakarta Sans'],
                'headline-md': ['Plus Jakarta Sans'],
                'display-lg': ['Plus Jakarta Sans'],
                'label-sm': ['Plus Jakarta Sans'],
                'headline-lg-mobile': ['Plus Jakarta Sans'],
                'body-lg': ['Plus Jakarta Sans'],
                sans: ['Plus Jakarta Sans', 'system-ui', 'sans-serif'],
            },
            fontSize: {
                'headline-lg': ['32px', { lineHeight: '1.3', fontWeight: '700' }],
                'label-lg': ['14px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '700' }],
                'body-md': ['16px', { lineHeight: '1.6', fontWeight: '500' }],
                'headline-md': ['24px', { lineHeight: '1.4', fontWeight: '700' }],
                'display-lg': ['48px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '800' }],
                'label-sm': ['12px', { lineHeight: '1', fontWeight: '600' }],
                'headline-lg-mobile': ['24px', { lineHeight: '1.3', fontWeight: '700' }],
                'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '500' }],
            },
        },
    },
    plugins: [],
};